services:
  awesome-build:
    build:
      context: .
      dockerfile: ./build/dockerfile
    image: awesome:build
  awesome-web:
    build:
      context: .
      dockerfile: ./dockerfile
    image: cbmarie255/awesome-web:${CURRENT_GIT_REF:-main}
    ports:
      - 80:9999
      - 443:9999
    restart: always
