- hosts: production jenkins
  tasks:
    - name: Updates apt cache, upgrade, and install packages
    shell: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y docker.io make
    - name: Docker setup
      shell: |
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usernod -aG docker ubuntu
