---
name: module3_task1
on:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      - name: Change to directory and run make help.
        run: |
          cd module3_task1
          make help
